### ISSUE TITLE
Wrong property used for version in script src

### ISSUE THREAD

**Issue by akshaymagapu** [maxandriani/ngx-hotjar#17]
Wrong property used for version in script src, I think it should be **hjsv**

Actual uri = `https://static.hotjar.com/c/hotjar-${hjWindow._hjSettings.hjid}.js?sv=${hjWindow._hjSettings.version}`;

Expected: uri = `https://static.hotjar.com/c/hotjar-${hjWindow._hjSettings.hjid}.js?sv=${hjWindow._hjSettings.hjsv}`;

**Comment by maxandriani** [comment]
I'll fix that. Meanwhile you can use `uri` property to workaround this issue.

`forRoot(trackingCode: string, version: number = 6, uri?: string)`

**Comment by akshaymagapu** [comment]
thanks, @maxandriani for the quick fix 👍
