### ISSUE TITLE
Question: Is it mandatory to use NgxHotjarService or NgxHotjarRouterModule?

### ISSUE THREAD

**Issue by akshaymagapu** [maxandriani/ngx-hotjar#19]
When we are not using NgxHotjarRouterModule or NgxHotjarService, we are getting an error
![image](https://user-images.githubusercontent.com/13298615/85301488-2d8de200-b4a8-11ea-8c3f-f107bff6715d.png)

@maxandriani  Is it not optional to use service and router module?

**Comment by maxandriani** [comment]
@akshaymagapu Seens like I forget to add ‘NGX_HJ_FN’ in NgxHotjarModule providers. Until I fix that you shall import either NgxHotjarHouterModule, NgxHotjarService, or @Inject(NGX_HJ_FN) hj: HjFn;

**Comment by akshaymagapu** [comment]
@maxandriani thanks for the clarification. Yeah, importing service for now 👍
