### ISSUE TITLE
Doesn't seem to work with angular 10

### ISSUE THREAD

**Issue by sckill** [maxandriani/ngx-hotjar#27]
**To Reproduce**
1. Create an angular based app.
2. `ng add ngx-hotjar` or 

**Expected behavior**
Dependency should be added.

**Screenshots**
![image](https://user-images.githubusercontent.com/77717792/105572438-f6b4ce80-5d0b-11eb-8ecf-cba0f7dc37bc.png)

--force, or --legacy-peer-deps options don't work either, and fail with the same error.

**Additional context**
Please upgrade the package to support angular 10 (and 11).

**Comment by BruneXX** [comment]
Hi Guys, any update on this? even any workaround? thanks!

**Comment by maxandriani** [comment]
https://github.com/maxandriani/ngx-hotjar/commit/2638a549dbddf09c26faa9fbae1849de138e1830
https://github.com/maxandriani/ngx-hotjar/commit/8520eba0ccbdb8259e4dfe196c4e651b001b8e07

I don't have so much time to keeps does projetos up to date anymore! So if you guys need something urgent, be my guest to fork this repo, upgrade the ng version and subimit a pr.
