### ISSUE TITLE
Disabling module based on cookie consent

### ISSUE THREAD

**Issue by sambeaven** [maxandriani/ngx-hotjar#28]
**Is your feature request related to a problem? Please describe.**
I'm trying to implement some cookie consent work and need to disable the module programatically (i.e. keep it disabled until the user has consented), but there doesn't seem to be a way to do this.

**Describe the solution you'd like**
Be able to load the module in a disabled state (e.g. ```NgxHotjarModule.forRoot(enabled: false)```), and then to be able to enable it again within the NgxHotjarService

**Describe alternatives you've considered**
Our current implementation allows us to turn it off based on an environment variable, but this only works with variables that can be evaluated statically.
Currently I'm looking into my own implementation, sticking the hotjar code in a component I can disable. But it'd be a lot neater to be able to do this from within the module!

**Comment by maxandriani** [comment]
You can import NgxHotjarModule w/o forRoot and call the function `hotjarInitializer(IHotjerSettings, Document, Window)(); ` when you are ready to go.

You can read more about it on this thread https://github.com/maxandriani/ngx-google-analytics/issues/40. This two libs have the same architecture.
