### ISSUE TITLE
Use track code

### ISSUE THREAD

**Issue by silentbil** [maxandriani/ngx-hotjar#7]
Sorry for the stupid question, but im not sure how to use the tracking code:
NgxHotjarModule.forRoot('traking-code')

the tracking code from hotjar is a long script <script>function(hotjar.......) 
All of that need to go inside??
can i get an example ?
Thanks

**Comment by maxandriani** [comment]
Hi @silentbil! Don’t worry. The tracking code is just the “site id” inside hotjar tracking code. It is a small number with only numeric digits. You can also find this number on Hotjar Site Dashboard like the follow image.

<img width="375" alt="Hotjar" src="https://user-images.githubusercontent.com/7096439/67944826-326df080-fbbc-11e9-9bc5-178d198f56f6.png">

**Comment by silentbil** [comment]
Thanks!
